[workspace]
# Use the newer version of the cargo resolver
# https://doc.rust-lang.org/cargo/reference/resolver.html#resolver-versions
resolver = "2"
members = ["benchmarks/rust"]

[profile.release]
codegen-units = 1
incremental = true
lto = true
opt-level = "z"
