name: 'rust installation'
description: 'Setup rust and cargo'
inputs:
  toolchain:
    description: 'The rust version to use. By default this uses the `rust-toolchain.toml` file'
    required: false
  targets:
    description: Target triple to install for this toolchain
    required: false
  components:
    description: Name of the group of components to be installed for a new toolchain
    required: false
    default: clippy, rustfmt, rust-src

runs:
  using: 'composite'
  steps:
    - name: rust installation
      uses: dtolnay/rust-toolchain@master
      with:
        components: ${{ inputs.components }}
        toolchain: ${{ inputs.toolchain }}
        targets: ${{ inputs.targets }}

    - name: add cargo bin to path
      run: |
        echo "$HOME/.cargo/bin" >> $GITHUB_PATH
      shell: bash

    - name: verify rust install
      run: |
        echo "verifying rust '${{ inputs.toolchain }}' ..."
        rustc --version
        cargo --version
        cargo clippy --version
        rustfmt --version
      shell: bash

    - name: share rustc hash
      run: |
        echo 'RUSTC_HASH=${{ steps.rust_toolchain.outputs.rustc_hash }}' >> $GITHUB_ENV
      shell: bash

    - name: generate cargo lockfile
      uses: actions-rs/cargo@v1
      with:
        command: generate-lockfile

    - name: cache rust
      uses: Swatinem/rust-cache@v1
      with:
        sharedKey: ${{ inputs.targets }}
